### ISSUE TITLE
missing "City Rule" achievements

### ISSUE THREAD

**Issue by elfosardo** [teamducro/gloomhaven-storyline#102]
The "City Rule" global achievements are not there and there's no way to add them.
Also, the function to manually add an achievement doesn't seem to work.

**Comment by dducro** [comment]
Thanks for reporting, I'll fix this this week. :)

**Comment by dducro** [comment]
Could you please send your progress? This could help me to diagnose the issue.
Manually adding achievements is only enabled for achievements gained by other means than completing scenarios.
City Rule: Militaristic is added automatically.

**Comment by elfosardo** [comment]
@dducro I don't have the City Rule: Militaristic achievement at all and I can't search/add any achievement manually.
I've attached a file containing the url of the campaign
[gh-campaign.txt](https://github.com/teamducro/gloomhaven-storyline/files/6295867/gh-campaign.txt)

**Comment by dducro** [comment]
Thanks for the link! I published a fix that will solve your story state and City Rule: Militaristic should be visible for you!
Let me know if it helps.
Enjoy the tracker! :)

**Comment by elfosardo** [comment]
@dducro hi!
I imported the link again in a private session in Firefox and an incognito session in Chrome, but it still doesn't seem to work.
I ended up re-creating the campaign from scratch as in this case all works fine.
I guess we can close this, even if it's not fixed, but I wonder if I can provide more info to help fix the issue in case someone else experiences it or happens again in the future.

**Comment by dducro** [comment]
Hey,
When importing your link for the first time the achievement is missing indeed, I can see what I can do about that.
But when you refresh once the storyline state is corrected and City Rule: Militaristic is added, see screenshot below:
![Screen Shot 2021-04-13 at 10 33 15](https://user-images.githubusercontent.com/2156884/114522488-b64a5a00-9c43-11eb-968d-df0d4583cbc0.png)

**Comment by elfosardo** [comment]
@dducro interesting, I tried that a couple times in the incognito tab and it didn't work, I tried it in the tab I had already opened in the normal chrome session and it worked!
I wonder if something in the incognito session was blocking that.
Anyway, thanks!
