### ISSUE TITLE
Scenario 82 causes the Add Items dropdown shows NaN as an option

### ISSUE THREAD

**Issue by sirrus233** [teamducro/gloomhaven-storyline#105]
Steps to reproduce, from a fresh campaign:

1. Mark Scenario 82 as Complete
2. Choose Conclusion A as the completion option
3. Tick the box to indicate you collected treasure 62
4. Go to the hamburger menu in the upper left, and open the Items page
5. Click the + button to Add an Item

Instead of Items 110 and 115 ticked (the contents of treasure 62), you will see that Item 110 is added, Item 115 is not added, and there is a ticked box for NaN after all the other numbers.

It seems like what should happen is that when marking Scenario 82 as complete, if you select Conclusion A you should also indicate which item was sacrificed, and then only that item should be added to the collection.

**Comment by dducro** [comment]
Thanks, I'll take a look

**Comment by dducro** [comment]
Items 110 and 115 will be unlocked, no NaN :)
