### ISSUE TITLE
Items given directly as scenario rewards are duplicated by items from town prosperity

### ISSUE THREAD

**Issue by sirrus233** [teamducro/gloomhaven-storyline#106]
Items are automatically unlocked on the items page by increasing the prosperity level of the town. However, some of these items can be obtained earlier in the game by completing certain scenarios, or found in treasure chests. When a scenario awards a particular item, and then that item is later unlocked via prosperity progression, the item appears twice in the items sheet.

As an example, item 41. Steps to reproduce, from a fresh campaign:

1. Mark Scenario 71 as complete (this awards item 41)
2. On the Party Sheet page, set town prosperity to any value above level 5 (unlocking items 036-042)
3. Go to the Items page, and sort items by name - you will see two instances of item 41.

I can confirm this behavior occurs at least with items 33, 41, 44, and 45.
Item 41 is awarded by scenario 71.
Item 44 is awarded by scenario 57 (treasure 3).
I am unsure about the others.

**Comment by sirrus233** [comment]
Possibly related to #103 ?

**Comment by dducro** [comment]
Thanks for reporting, I'll see if I can fix it soon! :)

**Comment by dducro** [comment]
If item 41 is unlocked via a treasure and via prosperity it won't be shown double.
