### ISSUE TITLE
Sorting by region doesn't seem to work

### ISSUE THREAD

**Issue by tsmigiel** [teamducro/gloomhaven-storyline#120]
Sorting by region on the scenario list page doesn't seem to sort correctly.

**Comment by dducro** [comment]
What do you expect to happen?
It sorts all scenarios with regions as follows: scenario must be visible and it most have a region.

**Comment by tsmigiel** [comment]
For example, in the region column it says things like "Gloomhaven", "Crypt", "Dagger Forest", etc. I would expect all scenarios with the same name to be together and sorted Alphabetically overall. The reason I want to sort is to see all the quests with "Gloomhaven" because that is my character's quest. Right now I have multiple completed scenarios in Gloomhaven and they are not grouped together when I sort by Region.

Locked scenarios don't show a region name, so I would expect them to be grouped together. Whether a scenario is completed or not I would not expect to effect the sort.

There seems to be the same issue when sorting the "Chapter" column.

**Comment by dducro** [comment]
Thanks, I see, so you would also expect all future hidden scenarios to appear next to the visible ones.
I don't know if that makes the list more or less readable.
You may use the filter on region in the top right to filter scenarios to see only scenarios in Gloomhaven for example.
I'll think about your request on changing the sort on region and chapter.

**Comment by dducro** [comment]
Ah! Is see now, the list is not sorted at all in firefox. This issue is not present in Chrome. I'll fix this in the near future! :)

**Comment by tsmigiel** [comment]
Phew. I was wondering if it might have been a browser issue. In which case, I am sure we probably agree about how it should sort.

**Comment by dducro** [comment]
Thanks for reporting!
The issue should be fixed, please let me know if it's working as expected now.
Hope you enjoy the tracker!

**Comment by tsmigiel** [comment]
Looks great. Thanks!
