### ISSUE TITLE
(Spoilers inside) How about adding details for some of the Sealed records?

### ISSUE THREAD

**Issue by tsmigiel** [teamducro/gloomhaven-storyline#122]
There are 3 scenarios unlocked by the town records. There is some story behind them that could be added as "preceding events", and looking at the first 2 they also don't seem to have a summary after completing.

These 3 from town records are currently in the "Sealed" chapter of the story line. Given their shared story line, would it be useful to create a new chapter called "The History of Gloomhaven" and put those 3 scenarios in there?

**Comment by dducro** [comment]
That's a good idea! I I'll add the preceding events text from the town records.
I'll see what I'll do with the svg (storyline flowchart), changing this is quite time consuming and would rather focus on other features.

**Comment by tsmigiel** [comment]
Cool. Yeah, changing the chapter does not have much benefit so it wouldn't bother me if you closed the issue after adding the preceding events.

**Comment by dducro** [comment]
72 is added! :)

**Comment by tsmigiel** [comment]
Just tried it out. Looks great.

**Comment by dducro** [comment]
72 is added! :)
