### ISSUE TITLE
Tracking item counts available in market

### ISSUE THREAD

**Issue by tsmigiel** [teamducro/gloomhaven-storyline#123]
Would it be difficult to add an "available to purchase" count to items? Or something similar to that.

When playing remotely with friends, we often spend our own separate time planning our characters, including buying and selling items. It would be nice to know which items are actually available to purchase in the market. And if we are all using the storyline app we know the counts will be up to date too.

For example, on the Item page:
- add a number column something like "Available in market"
- after clicking an item to open its info modal, add a UI that can change that number. e.g., "buy"/"sell" buttons 

I am /not/ requesting any tracking of who purchased what or how much gold someone has. Even though that might eventually be nice too. :)

**Comment by tsmigiel** [comment]
I know you are working on other things. Of course, prioritize how you like.

**Comment by dducro** [comment]
The character sheets are rolled out and I added availability numbers to the items as well as icon links to the character sheets that hold the item.
Hope you like the update! :)
