### ISSUE TITLE
Recent few days I have been getting "Failed to save progress, try again later." messages

### ISSUE THREAD

**Issue by tsmigiel** [teamducro/gloomhaven-storyline#125]
I am using FireFox 89.0 (64-bit), on MacOS 11.0.1 (20B29) Big Sur.

For example, if I try to add item 130 on my party sheet on this computer I get the message. Then I go to my iPad the new item is not there, as expected because of the failure.

Then I sent myself a new link to the campaign, and now it seems to be working again.

So I am not sure exactly what fixed it. But maybe adding a message about "try getting a new link to your campaign" would be useful in the failure message? Or a link to a trouble shooting page with tips like this?

**Comment by tsmigiel** [comment]
I also tried on Chrome before sending a new link, and it was working there.

I did update my FireFox recently, so I wouldn't be surprised if that was related.

**Comment by ghostdoglt** [comment]
I opened it in FF private mode, and restored campaign from here (new link was sent to email) and it worked. I guess link needs to be regenerated

**Comment by dducro** [comment]
Thanks for reporting.
Correct, Laravel, the framework used for the api was updated. This caused the current sessions to expire.
I had the same problem on Saterday, I'll try to update the error message to request a new link if the problem persists.
I will try to see if I can send new recovery links to the users who haven't already.

**Comment by dducro** [comment]
The issue is resolved, old sessions from before the update are valid and accepted again.
