### ISSUE TITLE
Item List Doesn’t Show Non-Prosperity Items Found During Campagins

### ISSUE THREAD

**Issue by Minneth** [teamducro/gloomhaven-storyline#128]
For example, I unlocked Volatile Bomb but this does not show in the items list. I also cannot manually add it as it will only show items within my prosperity level. I can confirm that the campaign this item was received in shows that the item was successfully acquired.

**Comment by dducro** [comment]
The item should be available in the list after checking the treasure checkbox on scenario 26.
Could you try to uncheck and check it again and see if that helps.
If not, could you share your storyline with me? I'll take a look.

**Comment by Minneth** [comment]
This seemed to resolve the issue, but it also appears to be a problem with a few other items we've gained so far such as Hooked Chain and Doomed Compass.
________________________________

**Comment by Minneth** [comment]
Forgive me, Doomed Compass was actually unticked. I'm unsure about Hooked Chain though, it looks like a prosperity item I haven't unlocked yet, though I have it. Perhaps it's not an issue but will confirm when I've found where it came from.
________________________________

**Comment by Minneth** [comment]
I can now confirm the issue also occurs with Hooked Chain. It was acquired in scenario 70 and has been ticked within the app, but it does not show. I ticking and reticking does fix the issue however but this isn't really a solution.
________________________________

**Comment by dducro** [comment]
I see, I'll add some checks so unlocked items are available in the list without unticking and reticking.
Items obtained by completing scenarios or treasures should automatically be available in the items list.

**Comment by dducro** [comment]
1f7d56334a7e9fb46f8b8d2bfbb79c53d5245b39
