### ISSUE TITLE
Scenario 17

### ISSUE THREAD

**Issue by psychostar** [teamducro/gloomhaven-storyline#129]
We unlocked Scenario 17 through an treasure found in scenario 37. There currently is no way to Unlock the scenario in the app. In the scenario list it is greyed out, and it does not appear in the scenario tree. We have scenario 13 locked so we cannot unlock there either.

**Comment by SteveRodrigue** [comment]
In my own campaign I was able to unlock scenario 17 by checking the treasure (mark the treasure as found) on the scenario 37.

**Comment by SteveRodrigue** [comment]
![Screenshot_20210725-153335](https://user-images.githubusercontent.com/1983108/126911132-d83de986-1dff-4ac8-beb3-cac2ee85709f.png)

**Comment by psychostar** [comment]
That did not work, scenario 17 did not unlock through that check box

**Comment by psychostar** [comment]
<img width="832" alt="Screen Shot 2021-07-25 at 2 34 35 PM" src="https://user-images.githubusercontent.com/1740093/126911160-badf9ad1-40bd-477c-8060-25a0de50b41c.png">
<img width="674" alt="Screen Shot 2021-07-25 at 2 34 25 PM" src="https://user-images.githubusercontent.com/1740093/126911162-e80a3510-7859-4eac-b825-0ea6cb34990a.png">

**Comment by psychostar** [comment]
So we just finished scenario 37, and after you complete the scenario and mark Scenario 37 as complete, you can then click on scenario 17 in the bottom right hand corner of the Scenario 37 completed screen and then mark scenario 17 as incomplete.

But if we lost Scenario 37, scenario 17 should still be unlocked and scenario 37 still marked as incomplete. So there is still a bug in this, that Scenario 17 does not unlock with checking the box.
<img width="546" alt="Screen Shot 2021-07-25 at 3 05 42 PM" src="https://user-images.githubusercontent.com/1740093/126911961-3dfd0d3f-00fe-4abf-9ff8-10288c36374f.png">
<img width="556" alt="Screen Shot 2021-07-25 at 3 05 27 PM" src="https://user-images.githubusercontent.com/1740093/126911962-bab5e76e-1bd5-430b-96a3-8f88a53bc028.png">

**Comment by dducro** [comment]
I'm sorry for the late response, I was on a short holiday.
I removed the check that the scenario should be completed to unlock other scenarios via treasures in commit: 4747e90858e7145081d3123781c8cd2e0f373b82
In theory you still unlock 17 even when you lost scenario 37 and looted the treasure.
