### ISSUE TITLE
Power of Enhancement not unlocking proper scenarios

### ISSUE THREAD

**Issue by AyeJayTwo** [teamducro/gloomhaven-storyline#132]
Completing Scenario 14 should unlock: 7, 19, 31, 43
Right now it doesn't tie back to the appropriate scenarios, so may need to adjust that in the links.

**Comment by conerck** [comment]
Only scenarios listed in the "New Scenarios" box are unlocked.
Circles numbers in the conclusion text are just hints on where the story continues.
