### ISSUE TITLE
Scenarios 35 and 36 blocked

### ISSUE THREAD

**Issue by mpv89** [teamducro/gloomhaven-storyline#144]
Hello,

Scenarios 35 and 36 are blocked in out campaign tracker, but all the requirements are met: `A Demon’s Errand (Party) COMPLETE and The Rift Neutralized (Global) INCOMPLETE`.

Screenshots below, trying to avoid spoilers to others..

<img width="289" alt="image" src="https://user-images.githubusercontent.com/7635169/136481835-e4720ff0-4b1b-40b0-992f-8c6c71c78bed.png">

<img width="64" alt="image" src="https://user-images.githubusercontent.com/7635169/136481925-2baa3dc2-f885-45d0-a338-8e8212fe894e.png">

Could this be a bug or am I just missing something?

Thanks!

**Comment by dducro** [comment]
I was gonna mention, looks good to me xD
There were some changes made to requirements, this probably caused it.
I pushed a fix two days ago, hance the scenarios unlocked after a refresh.
Let me know if the issue returns.
