### ISSUE TITLE
Broken image for sticker on storyline list

### ISSUE THREAD

**Issue by cwhits** [teamducro/gloomhaven-storyline#146]
I'm on mobile right now and have only tested this on mobile but the first scenario listed for JoTL and Gloomhaven have a broken image for their sticker.
![Screenshot_20211019-070542](https://user-images.githubusercontent.com/7746625/137897821-28143f3f-469a-40a2-8e36-52a464089059.png)

**Comment by dducro** [comment]
Thanks! Will fix tonight :)

**Comment by dducro** [comment]
Resolved.
