### ISSUE TITLE
Unlocking scenario 17 (again)

### ISSUE THREAD

**Issue by mattes939** [teamducro/gloomhaven-storyline#151]
I have just discovered your awesome application. Unfortunately there seems to be again an issue with unlocking scenario 17 via treasure 49 in scenario 37. The scenario is missing a button and is not visible in story schema.
![image](https://user-images.githubusercontent.com/7654792/143841670-530ddbe7-1cfc-4c2a-9271-2d7dd2713898.png)

[Here is a link to my storyline configuration, if it helps.](https://gloomhaven-storyline.com/tracker#/shared/1/local/N4Rozg5gFgtAjAIgFyjAFxAYwDQjQbQQHYEBdAX1zADNMYBOANmVQwEtKQBDCAYQCUW3MIQDiAgLIJsCcfwAi02ZLKcucqSm4B3EHFyYA9vpAAbEAAZOYKMARcATpihsAbgFMAJryiOumNHcHMBZKBGc-AKCAVQA7U0NMAGsQlAQAIUEkPRleAAlkHIQAZQB1Qv0EABUASQqZYt56hAkq5vliwosZAFEAGS6G9MGSzuzukoBpEYA5McsG6JH0npGARU0FhAAFAvGZdLb9hHksrf5REflNibyjrYA1cvHOCOAwzDY0AE8WBERspUAEzNADMzQALM0AKzNZiAmQkBEIAAczXozTgFkxAKKcBByLg4MJUMJsMJ8LxSLxaMJGORQOxDNxwIJRSBxPZpPZ5PZlOB1OBtPZ9KKoKZYtxE1BbOlnOl3OlvOllOl1OlwuloomEIlOqlMghssN8sNisNysNqsN6sNmsN2pk0L1ToNCGhxvdpvd5vdlvd1vdtvd9vdjoQjBdEbdjE9jG9jF9jH9jEDjGDjFDjHDRCjRDdRE9RG9RF9RH9REDRGDRFDRHDKKjKLdKM9KO9KN9KP9KMDKODKNDKPD9D1nDYnjscFFwO5ArBnMqushc4tMMXiILRZLZYrVZrdYbTZbbY7XZ7fYHQ5HUfobvonvo3vovvo-qY6OD9GFlXo4axEqVFiLIyFinpYhu-wWL6WL+ligZYoKoEWD+yH-liIxwFhmH4jikFYau-xwHBcD8qBcDBlhoZYf+jKYUCbr4uBHKYkChH4nBQIIUClFAqh-xAv+4qYqCjEyiJ3pEjBoJwaCCGgpRoLUaC-7LsccAQoxRqYRCkkQjBEJwRCCEQpRELURC-7Ol0nAAA5sJUDiGFwnh-CBCBspUkGEbylRkcQzT8TOyE4qxImYuxvmgf5FGYvx07NHRzKJZ5MgsQyhFAlFHn+TxiX8YJYKATIokjOJxygt6oK+jJZWBgpZWhipIxqVsmktZ6uktb6hktYGpktaGlkjNZxzQm6Hojd60K+tC-rQoG0LBtCobQuGkYjIwMZxgmSYpmmGZZg2p42bgACudhRm6nrerNm0jAONnWNAMBrUI6AgBwuBcNsABiYygFwugmEYJjmFYVAvQSrBYLgBARiQFCQ7AxIwzgeCEMmqjIzApJo3DhBKUoxnY9w2wAFLbEIQM5Fgxi4ODz2wLSMMAEZMww70YJgaiiFU8h1FoNMg-TZiWBz2FaB97M47hUvcwTCDVaT6g9AA8oLgPAwYouM7L8L4xj-yk5AsBwCz4AK0b8Ym1DFsfej8PiUj4BQ3jlufRzWVc7DRsrSr2z800Qu6N0dNh+YcAc5VXMIA47gAI5nWw8eudH7sO4rLEu+o-MAzotOgwz4s4+Shvw1CaVoi7pswAbHuO4Q1k59s8jDCHhe6yXZMAIKawXItg93teFfLvsV4gOd8z0igd4PxcQ67ZtMuXhDYTXL0aT7jc5bbZv0qv-yI2o2w9-Iqwd2HRgR3oXsAofxF7zAQLQw3WeT2oEA9-wRyAyIsjfyUKIHuAwZDAP4CCMBPcmhT0AZfHWN8o441KmPHe2Yn61VQYrLaGD67S15gIWeWsFjh2Lkg7gwCBjwNIWLchtdepYKNqWJ+w0x4yyXq9FeDdeZVG2BfYh88xaLx+o0am2s6ZD0XiPJEMMvocPSofZqiIQQb1gFxbe2DmCqNxqjN+RtaqwN-gPHWEIF64AALZcG7j9KoWQBE60kSfX6wd7ESIXrzUo7dXFFyETw-gMwxGd0cd9cBr8aZX0MIg3m0DAmCL1hwhqjCK4Ym0UTVB0cD4ezkTYqoRjhYOPcTjAaSS15oidMfEJ6sXHGLpkCQpHDxqx3jknFOXgEAn34D3WJBTfFFIzuwDm5kNHWyhFPKpYTxE+PibXSa6TS66IdhzGawz4be20UtFZhMlAvyfv7OZHCcH7NrrGTZYYn5Y32eoHuVQJlBPqccvBVt4akSUHJFWwCqi6PyW43pByZHcJCdc923ypnDxepmU5MdtHoKOS9fMPs5G10LNvDmxYUU40rAijmzZTkQu0e2dFZN0heJqaCsOljb44yfKc5ZLce6tG6T88GFirF0JeqOU5CVtHVh9lAcg5AgA)

**Comment by dducro** [comment]
Thanks for reporting! I noticed this, I'll add a test and fix the issue soon! :)

**Comment by dducro** [comment]
17 is now available in your campaign 😃
