### ISSUE TITLE
Item 26 - Oak Charm

### ISSUE THREAD

**Issue by Limb** [teamducro/gloomhaven-storyline#152]
We are currently playing a new Jaws of The Lion game, and are only up to scenario 6. However one of our first city events gave us item 26 - Oak Charm. I can not assign this item in my player inventory since it does not show up in the Items list. I'm guessing this is because it doesn't get "unlocked" until a later scenario, but obviously this is contradictory since we got the item during a city event.

Can a toggle be added to allow the Oak Charm to be enabled before it is unlocked?

**Comment by dducro** [comment]
Thanks for the feature request, I'm not sure when to add this because of the holidays.
I'll add a way to add items obtained via event cards to JotL.
Enjoy the tracker!

**Comment by dducro** [comment]
Item 26 can be unlocked from the items page in JotL :)
