### ISSUE TITLE
Incorrect trigger for Personal Quest #524

### ISSUE THREAD

**Issue by JesusLopezCh** [teamducro/gloomhaven-storyline#156]
Spoiler:

<spoiler> Personal Quest #524:
 - Kill 20 Elite Monsters , but fulfill condition is triggered at 12 instead. </spoiler>

![personalQuest524](https://user-images.githubusercontent.com/7446271/149008806-ad12ed03-de16-4e7d-9731-87b23b89886f.gif)
!

**Comment by dducro** [comment]
Thanks for reporting, deployed a fix!
6687acd56b131defe5e4a0583da10e8d655bea79
