### ISSUE TITLE
Feature Request: Personal Quest Hidden

### ISSUE THREAD

**Issue by haudi31** [teamducro/gloomhaven-storyline#163]
Would it be possible to make the personal quest hidden. Only by clicking on the Image will turn it visible again. So I can check the characters of my friends without being spoiled. 

Can also be done to set a password. So no one can see your personal quest. If you forget your password, you can still delete your personal quest and add it again. This would eliminate the requirement for a "reset password".

**Comment by dducro** [comment]
Just released hidden PQs!
