### ISSUE TITLE
Features Requests

### ISSUE THREAD

**Issue by dennispat** [teamducro/gloomhaven-storyline#166]
Hello,

I would like to track the Card Abilities for each character (+modifications).

In addition, the background with the transparency is a bit dizzy.

Thank u. Great Job guys, i just bought it :)

**Comment by dducro** [comment]
Thank you for your feedback!

I'll change the background transparency, definitely agree.

Card Abilities cards is planned for a future update!
A bit unrelated, solo scenarios are currently in development for the next update!

+modifications will be an iteration after that, dependent on how developments go.

**Comment by dducro** [comment]
The background is not as transparent anymore.

**Comment by dennispat** [comment]
Respect!!!
