### ISSUE TITLE
In some browsers it shows invalid release date in change log

### ISSUE THREAD

**Issue by dducro** [teamducro/gloomhaven-storyline#171]
<img width="629" alt="Screen Shot 2022-02-22 at 00 45 31" src="https://user-images.githubusercontent.com/2156884/155039310-241cf3de-f2cb-4bad-b1bd-c9c0f82fb467.png">

**Comment by jgwehr** [comment]
Experiencing this as well, Firefox 97.0.1 (64-bit). It's been happening since one of the 1.x release (though I can't remember when I would have first seen it)

Works fine using MS Edge or Chrome.

**Comment by dducro** [comment]
Thanks, yeah, I'll have to look into this one, I changed a date library a while back to a faster one. This caused the issue.
