### ISSUE TITLE
German Perks not translated

### ISSUE THREAD

**Issue by haudi31** [teamducro/gloomhaven-storyline#176]
The perks in the german Version (in the Charaktersheet) are not translated.
Example: "Add two WUNDE cards"

Also the language is called "Deutsch" rather than "Deutsche".

**Comment by dducro** [comment]
I have someone  helping me with the German translations.
A lot more translations are supported in the current version, however they still need to be translated.
Perks will be supported soon, if I need help, are you interested to assist?

**Comment by dducro** [comment]
Please send me an email at support@gloomhaven-storyline.com, I'll add you to slack.

**Comment by dducro** [comment]
I'm closing this issue, more translations are in the works :)
