### ISSUE TITLE
"Buy" items from items-list

### ISSUE THREAD

**Issue by Termedea** [teamducro/gloomhaven-storyline#179]
A nice feature would be if you could assign items to characters straight from the items list (instead of from the character's page). Maybe even simulate buying the item. 
The usage could be something like this: 

1. you click an item to bring up its details
3. you can chose character from a dropdown or similar to assign that item to the character
4. the character provides the cost (with prosperity discount applied)
5. the gold is subtracted from the "Gold"-field on the character's page 
6. the item shows up under "Items" on the character's page.

Alternatively, if it was already added before the campaign tracking started, it would be possible to just add it without buying it as well.

**Comment by dducro** [comment]
I'll most likely add this feature in the future! :)

**Comment by dducro** [comment]
<img width="565" alt="Screen Shot 2022-04-02 at 14 58 24" src="https://user-images.githubusercontent.com/2156884/161384573-e9fc58b8-574a-43c1-ae53-4238f2ff298f.png">
