### ISSUE TITLE
Cloud sync - multiple devices erase each other's updates

### ISSUE THREAD

**Issue by nabil-sonder** [teamducro/gloomhaven-storyline#184]
I'm not sure of the context, but we play each with our own phone to update either team level information of character information, and more often than not it seems we keep erasing each other's changes. Is it a known issue? Are we doing something wrong? For context we are using the paid subscription.

**Comment by dducro** [comment]
Thanks for reporting.
Are you changing information at relatively the same time? Or at completely different times?
Can you send me an email, so I can get your specific campaign and please provide as much detail as possible about when the over writing occurs.
I'll see what I can do for you.

**Comment by dducro** [comment]
I thought about synchronization between users and ways to improve it, I plan to improve it quite a bit so you don't override each others changes!

**Comment by dducro** [comment]
Currently in testing phase! Planned for next release!

**Comment by dducro** [comment]
This is in production for some time without issues, let me know if you still experience overriding character info.

**Comment by nabil-sonder** [comment]
Very cool! We haven't really played recently, and I haven't had the chance to look into the details, but will report back with updates.
