### ISSUE TITLE
Completion of scenario 98 in “Forgotten Circles” allows to unlock either scenario 102 or 103, but not both.

### ISSUE THREAD

**Issue by DrDonik** [teamducro/gloomhaven-storyline#187]
There is the possibility that scenario 98 unlocks both scenarios 102 and 103. Currently, unlocking only one is allowed through mutually exclusive radio buttons. These should be checkboxes instead.

**Comment by dducro** [comment]
It looks like the logic in FC is broken after an update, I'll fix it asap. :)

**Comment by dducro** [comment]
Should be fixed :)
