### ISSUE TITLE
Share a read only mode

### ISSUE THREAD

**Issue by dducro** [teamducro/gloomhaven-storyline#189]
- all form fields shouldn't be editable
- can't change party sheet, character sheets, items or story state.

- A should have would be an exception to one character, this way the user can only edit it's own character.

**Comment by jgwehr** [comment]
@dducro Just quickly tested the read-only in Chrome/FF and it looks good apart from _one_ area:

1. I can click the various **Enabled Games**, but it doesn't seem to affect the actual functionality. 
2. I wasn't brave enough to try the **Transfer** button, but I'd disable it for now (?). I can see value in allowing someone to copy to a new/local campaign. But I wouldn't want someone I shared read-only to be able to **change the `Selected Campaign` and overwrite** my Campaign.

![image](https://user-images.githubusercontent.com/13216529/213208221-a1fb3b6e-55fd-42b9-823c-8ec357ac4141.png)

**Comment by jgwehr** [comment]
Ooh, and to add even more work to your plate!
A read-only version is most likely going to be shared with your other players (not the "game master"). In this case, it might make sense to implement https://github.com/teamducro/gloomhaven-storyline/issues/163.

_When a read-only link is opened, a given Character's "sensitive" information (like Personal Question) should be hidden by default._

**Comment by dducro** [comment]
Thanks for testing!
1. Enabled games effects the game selecter in the menu, available characters and (if enabled) available items from other games. This setting can still be used in read only mode.
2. Transfer campaign data is disabled in read only
3. I also removed the reset button. (This basically removed the campaign locally, nothing was persisted in read only mode.)
4. #163 I'll add this indeed.
