### ISSUE TITLE
Envelope X update not available

### ISSUE THREAD

**Issue by sjbarag** [teamducro/gloomhaven-storyline#191]
Heya!  In early 2022, the Envelope X reward received an update (:rotating_light: **SPOILERS IN LINK** more context on [r/gloomhaven](https://www.reddit.com/r/Gloomhaven/comments/seymvn/major_envelope_x_spoiler_x_reward_update/) :rotating_light:). Looks like v1 of that reward is available in-app, but not v2!

To further complicate things, info about the new version is in the same place as the old version :sweat_smile:

**Comment by dducro** [comment]
Support for ability cards is coming in next update!
I'd like to add V2 of X as well, thanks for the issue!

**Comment by dducro** [comment]
It's fixed!
