### ISSUE TITLE
Wrong Story Entries for Scenario 3 and 8

### ISSUE THREAD

**Issue by Azurewren** [teamducro/gloomhaven-storyline#2]
Scenario #3 incorrectly has the entry "The Merchant's Wrath".
Scenario #8 incorrectly has the entries "The Merchant's Secret" and "A Valrath's Best Friend".

These should be swapped.

**Comment by dducro** [comment]
Thanks for the feedback, I'll fix it tonight.

**Comment by dducro** [comment]
@Azurewren Hmm, this is kind of complicated, let me explain.

Let's take "The Merchant's Wrath" as an example.

I have 3 variants of the summery, the first is after scenario 2 is completed. the second after scenario 8 and the last after scenario 3.

The text of the quest changes depending on the state of the story.

Every scenario can have multiple quests.
However, this looks like we want to show the quest on the scenario depending on the decisions made by the party.

For this example show "The Merchant's Wrath" on 3 and 8 if they're both incomplete.
Show it only on 3 if it's completed first (and not on 8) and if 8 is completed, show it only on 8.

Let me know your thoughts.

**Comment by dducro** [comment]
The development branch can be views at this url: https://develop--gloomhaven-storyline.netlify.com/#/story

**Comment by grendelson** [comment]
It is very spoiler Heavy as is - If I mark ONLY 1,2,3, complete I SHOULD only see Merchants Secret, but I see Wrath, Secret, Tripping, Best friend.   If I send this to the party they automatically read ALL text present :)   Is this by design or due to fact you can reach 3 from multiple points?  ( I've tried adding and removing #5 completed for the rift.)

**Comment by dducro** [comment]
@grendelson I agree with you, I reverted the other quests from S3, Now S3 only has Merchants Secret and Wrath (intro). This is available after S2 is completed.
However as I stated above, at the moment it's not possible to show a quest line based on a specific state of scenario states. For example show Tripping or Best friend on scenario 3 after 8 or 9 is completed. If I add this logic I need help checking every quest summery text and add them to the correct scenarios. It will have to do for now.

**Comment by grendelson** [comment]
> @grendelson I agree with you, I reverted the other quests from S3, Now S3 only has Merchants Secret and Wrath (intro). If I add this logic I need help checking every quest summery text and add them to the correct scenarios. It will have to do for now.

Thanks a Lot!  I'm still Very early in game play otherwise I'd volunteer to proof read /test all paths :)   I'm trying to play spoiler free - but it's hard as the game owner - We're going to try using a Quest app form now on :)

**Comment by dducro** [comment]
We also want to play spoiler free, but also understand the storyline as it goes. That's why I created this app, the chart reveals itself as you progress in the campaign.
