### ISSUE TITLE
Shop modifier resets to 0 when entering the "Party Sheet" page.

### ISSUE THREAD

**Issue by assofohdz** [teamducro/gloomhaven-storyline#200]
Hey,

Just bough a PRO license. I like the work here. I just discovered that the shop modifier resets to zero when I create a snapshot. Nothing major, just a bit annoying really.

Kind regards

**Comment by assofohdz** [comment]
I just discovered its nothing to do with creating a snapshot. Whenever I enter the Party Sheet page, the modifier is zero. As soon as I +/- the reputation counter, it corrects itself.

**Comment by dducro** [comment]
Thanks for reporting, I'll fix it in an update! :)Have fun playing Gloomhaven!Sent from my iPhoneOn 25 Oct 2022, at 12:49, Asser Fahrenholz ***@***.***> wrote:﻿
I just discovered its nothing to do with creating a snapshot. Whenever I enter the Party Sheet page, the modifier is zero. As soon as I +/- the reputation counter, it corrects itself.
