### ISSUE TITLE
Can't manage to share my Jaws Of The Lion's campaign

### ISSUE THREAD

**Issue by tfabretti** [teamducro/gloomhaven-storyline#201]
Hi ! <3

I have a weird issue : I discovered your wonderful tool a few days ago, ahead of my play session when looking for campaign tracker. I love it ! Thank you ! <3
I use the free version.
I played with it a bit, to understand how it works and I created a campaign for JotL, as I will play this one first.
Then, the day of the game session, I wanted to prepare the tracker on another computer and I couldn't set a JotL campaign up. Impossible to have the JotL map displayed, the scenarios are always those of Gloomhaven and I can't have only JotL. I tried on 3 different browsers (Firefox, Brave and Edge), only checking the JotL checkbox did not work.
I went back to the computer I did it successfully previously and there, I realize only the campaign I had created previously works, on Firefox. Attempting to create a new one or share it on other browsers (Chrome, Brave or Edge) results in a base Gloomhaven campaign (map, scenarios, nothing in the players group...).
We played our first session without the tracker and I added the progress afterward. The behaviour is still the same : I can't share it (with the link) on another browser, I always end up with an emtpy base Gloomhaven campaign. I can't create a pure JotL campaign either, only the one I have on my Firefox, on a specific computer, works.

Am I doing something wrong ? I tried changing languages, removing the cookies and cache before pasting the campaign link but nothing worked :(

As a test, you can use [my link](https://gloomhaven-storyline.com/tracker#/shared/1/local/N4RozgVg9gLgNgWgIwCIBcowxAYwL4A0408CATOptjkTANopIAsKAuocbIgMyXjYBLQijAALAKbiYCEnEooAhgCccogQDdxAEwDCo5QpwxxSsJWGqDRkwFUAdnCg4A1mYwoASgHF0IJARQAEQBZX38UAAkAFTCAgDUAdTCOS2AUMiQccQAOAE4cbIQmXPEAViLSgCMANgRKnDJKhG5SnAAzbPFq0oU27kr5AFdBgS10dMyc-MLisoqauoamlvbO7t7+lADR8cStlDsFAFtxca9lLQFxOztxAAItQbu7AEuFOxh9yyVDYyUAOWOpzQKG+vxMYAAdIlIYcTvsAA4mZyBcRgHBKAQImACKB2Nx0UA4KDhLRonDjMHWUzQhKQpFKVyQgAMKEIRJJATJ6Mp+h+1KhMIZTNQ7NwUDIXPJvKsf0FdOFUIoYuJkpQ3IpIKpctp9ORUN4KolUp5Wr54JpQv1kJYRu4Js1oPNAt1ishpTZBA5pOlZtlENd1uqnu9Dpl-J1VsZUIA7CHxWqNeGLfK9dHIdk2awAnBxJo5GhwgJjEc3MALBIXGWUKy0CBmQFUHWG+lfC3eM2AixOygPT3gz24z3Mz3cm3G7X642m1PGBQe0gO7PmOPGH3lwPl0P68JFfJa3R69nGOhD8zj-Oz0RzwEO1ej13T1OH72nw3nzeUAOz8ehz+AiO97nsIACOgxop8GDCAolQCHAxZXGW0GwfBMAAJ4AAomAAMnm4gFmk852IMcBwLe6DEaRj5oJRZGvjRJF0QOtEBEOLEoCO7FjgxpHIXBxZoToUCDB86BIOEYiSDAAD6ADmQLjLI+zyfCIJKQEKniIECgwAo5gBAyYB4gocAAIrgVgHjiAiUBgMWUBKGh+koDAPz4nAOm4nYADS4hOX6EYBnsARtFccBaGAURQAAyjADnAmkww7CCSVjNsYwgjsASaKYXnjDldl4vs+hiOMJWiPscLAgcCk5nhBYoLm+b7AAHgi4xtcpUDheMsndWlKBKFIAhDScHxuINw2jdcMBmNsJbVsW4iluYHB2AcsBol8lauPIqjiFWq0Gfq8h7lBoEWZBaRgRBR2KChCFbe4MH8TiT3lnxqGYTh9XyC9X1YUouHNedeDCDGvQQ8y2RtAg2SVG0MZFG0ChaHUnRMAg1RaJUlRIHjJQxtkI6JSMGUoBDiMKNDsPw4jyOo+j4iY9juP40ghPE-syVBKEARVeMACCSg4qFOBXEo23+gCCkBSmkIhLCtUoMKqLopi2JeQSobqr6TrS1CituqyRqJnr2oBkb1qil64o+qa+uBTSVvpsqtuqmGcsui7TKGu7nK6w7FvO8EaZMra-tm0Hzo6j7UIeqbnuO-LceQsGieB46weG6HbpxhnSZe7HufWpmeDHk1+FifNy1IQE+2He4k4tjOLbzrOS4tt2s7ri2m4ttuLYjrO3HLs306rkg7ct53jbdy3veNv3jaD7uJ1N2+x5NkBF6b+RaA79R-70YfX5vtev7ny+gEfuwAQ3Vgzn-Y9df3a931A797hEYx+-sd27E+zsWYr-CmFFQGcVAdxWin0BJCREpBXIARJJSDkrLFA6kUCaUUlwZSQJtK6WcoZYyZlLpWRsnZOKjlnKuXeGADyOI8S+X8snb2fMUChXwhFKKsV4pDDJuMVK3NyZZRQAVPKIJxFFQCOVMqChSr83QQLOqINGq-QCJ1EEnUNL9V6rogIQ0cTTXGuMQxI1lozTmigJaK13A2KQmtDaxgrEN12u4VxDjjrRlOuvD699LryAfldMGARn5vWrGExCd0wkf2BlXZ6D10KAziQRMGISUBMGyEgao1RejMgQKUbIWgFBFCYOIMgixsglJwDGcQMZSjcGyEwZpMYBjuCESCTJ2TcltHyYU4ppTymVOqbU+pjTmlMFacI8Y0RKroOwu8LIgwlAPHuPofaUsnaAlUqwnU0Qlbwi8SickGtGH4lPByKOWcY4Bn2cbeMxJ7bXINpCO51sHkB0Lrs25UQw5Kg+U85MLo3npj9jrL52dXm-LdBHcF5sbk0hBUyBO-tAVFx+X8tOAKk6QqRbGD59pM5Ar2dC0uBKcUIqhHiyEY5y4qPiUWBazkPH7knquae+9ZzzwCIvM+g5VzDxbKPFu49GCt0bByxgs9GDcrXJPZejBV5HOrAeW+jY96tgPi+O8L5uzHz7Mfb8L4-zXyvu+T83EgIXwurdKCoTElRLtW-AGP0QaEXAVRFAHZ-4erokA0BIDPVsQgb6gI0DGKwPQvA0ShYWwoJktgtSuCNLoMwZpAheknXEMOKQiC5DbL2WoU62h7lPJML8sSn5+xOHhUijFKhCUUAdKbQI9K4xRFSPWpIiEeUZHyIqiCWRiidnKLUaoyucgNHtS0e1HRPUQR9R6gYqaFiTEgjMcY2a3MmV2J3X4kA607CbRcTtasLLzrKp8d4i9KAgmBICTeyJ71nUv2iYk2JX80gxOSZ+tJwhWiZCKW0NGSBmRkExs03ITRKhFKQAgZkuR8iVDIMzLQzJuADlJjzADBQtDAeQGBiDxRoOwfg4hnAyHUPoeDG2kE3g5k7POEoMkdwPDCVkqceuCLtnVUhd4A5nGVbIjVhiLEZztZ2wpS8-j9yjRou+TSGT7y5NSadlCJTrsPlXMrYprwmKwUJlU-LDT4ctNGZdCZ+OZmiXot05i9OkdzM6ks5CfOqKnMBhc2XdzNmFPqb026WlFcv7hEXRlJB1i90oFHkgCsB03FpFFeKzVHdVyyt5QqweAFVzConJPZLU9J7SpXAuXl2TJ5KqE9exLGrt4vkvNqs1x49VqpPq1o15rL5as69l7rx5LVHhtY-J1T7X7ftdfE91PE6LetAQA0B-rPWBrosGz1kDPXht4va9+0bIKgeQRIVBiaMHJqwam076adKZvLF4oyObzJ5usgWqh-kbsuTcvQstPkK22f89WsK3D618PaQIlKrbrEiIGp2-KPbpEoFkYO-tDHqqjoneMNHU6Oqzqwbohd+jJpGNXVu9dK6xpbprrYtI9ijoHqcVtLj8Wz2nrumdNIrP0l3vcJzvxL7wl-Qde9dJ43P5ut5x+t1f6LACXkDOcI7dwhLnCN3cI65wibnCNucIw9wgxby3WcI4lYhziN4uE3yvGyq6XibzXjZteNl1+kSccvZcBDIPLjgoxCIKrIFl9IgrXe5a9aK7gyXuCSu4NK7gsqWirgw22DgCIBDhCUFAVG+kQCDB58Hcgkw8gFCKCUcoTAqi1HqI0ZorQOhdB6H0NpX6BdjffT+0XP9PWzc9fNz1i2mKhrAdN3rXFfVxcbjVhc7LY9pdXBl1cvv-fRcnklgrkrTcLllUgMrCqkCVbC+gFsPNgqRdrs5NHhZh3VSY5ca4twHhPFeO8T4l6N59fVc-zVp8dU9YyU1nlZqL4BA611sfDfJ1kNsEsuoTmTm4C2M2hkFkHnjMIXvMKXksBXqsNXhsAMJjmgMyBWNLAgJTFDDDHDAjEjEwCjGjDBszFjDjHjATHUlzAkq9I6m9sLikvIK3jNr3p3n6r3stqxL3utnRJtnAMPgljWGyj2OHpPj2NPvysODlgvvlpPMvsVmvhvhVvHnOhlHvuTCENukfk6ifuEALCCMLKLAIOLCYIiL4uIa-nVp-g1p+B-n-l-q-gau1t-n3qfMAdav4ram9hukTlAQEM2gQdTEQXTKQeQUzCzDQezJzJmFgTgVxngV0jknkgUkUiUs0kMvUFUggDUnUg0k0i0nXrzswZGuLpNpquxO3nRNwT-v3nyuxKtnRIIWGkPgziPrYcuOPj2NKulquJlgKgoQuIvsoUVpPGofKhoc2MIDvtgbRpEDEBTq-EYWfuMAsnYEsisixushINYdVrYafPYbvK-h-s1hqu4Z+AAfwa-j4a1gNuar4beg+gEaTpYrviEaDhklkukb0pkQMjkRUnkSMkUeMqUa1NOskQpgUjgIBnhiBoRqUlBujFoHBghkhihkwGhnHowahBUdti6iLtURwX-HNr3t3v-r3q0QPlAp0U6IzqymPpIRPj2IMf2DPiMaOIoQuEvpMavpPOoQuNvrjhFjzPRqsfIDFsIOsTVIxhcPcGxoMBxocWIaqp+Kca7hqs4bqp4dcS4R1i4Sap-sAf1pvKAc5M2jhkBkieBiiSRuiWRliVRnHmDEAA/map). You're supposed to end up on the JotL map with a group of 4 characters. On all of my browsers (except the source one), it gives me an empty Gloomhaven campaign.

**Comment by dducro** [comment]
Thanks for reporting.

You can find the game switch on the bottom of the menu:

![Screen Shot 2022-10-27 at 14 07 57](https://user-images.githubusercontent.com/2156884/198280264-a876f088-7556-49b1-9ef4-f019f980293c.jpg)

I can add some functionality to switch to the correct game, where the link was created from.
At the moment a link always opens in Gloomhaven.

Hope it helps, have fun playing!

**Comment by tfabretti** [comment]
Oh, I get it, now !
If I uncheck all boxes except one, in the Settings, this combo box isn't displayed, not allowing me to select to only one I've checked.
Thank you very much ! <3

**Comment by dducro** [comment]
Ah, yeah! I forgot about that, It should only select one of the available games, I'll improve it in a future update.
