### ISSUE TITLE
Attack Modifier Summary

### ISSUE THREAD

**Issue by 1seanr** [teamducro/gloomhaven-storyline#213]
It would be very handy if there was a little summary like this near the perk area on the character sheets that would allow you to check your modifier deck to make sure you have the right number of all of the cards. In this spreadsheet, it automatically changes when you select a perk so that you know as long as your items and perks are correct you can recreate your modifier deck super easily.

![image](https://user-images.githubusercontent.com/26175502/211651593-cabca416-6c3f-4224-8737-0d80347c2cb7.png)

The small items limit count below is also very useful as a reminder

**Comment by dducro** [comment]
Thanks! Yes, this will be added in a future update! Very useful

**Comment by dducro** [comment]
![Screenshot 2023-01-20 at 00 47 57](https://user-images.githubusercontent.com/2156884/213590161-c84b44ea-9229-4557-bce2-3b3d73413fdf.jpg)

This is coming in a future update! Still a lot of mapping of perks to do.

**Comment by 1seanr** [comment]
That's a lot fancier than I was envisioning, it looks really good!!!

I am mainly a react/express dev so if there are upgrades I would find helpful on the app can do them if I find time, and if I do them and make a pull request and if you like them you can add them if you don't you can cancel them, is that all good?

I'd really like if possible to make a font selector in the settings like the language selector as I personally find the default gloom font really hard to read at a quick glance and would like the ability to change a font setting to make it a bit easier to read.

**Comment by dducro** [comment]
Yeah,
Pull requests are welcome, please let me know before you start to prevent double work.
A font selector in setting is a welcome addition, personally I would also like a more readable font.

**Comment by jgwehr** [comment]
GloomhavenSecreteriat has Perk info: https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/gh/character/brute.json#L45

I can easily transform this to map perks for the Characters, just need an idea of the schema you want to use @dducro

**Comment by dducro** [comment]
Ah, That's great, thanks!
No, I'll change my implementation to use this format, that will make implementing other games in the future easier.

**Comment by dducro** [comment]
I'm about half way adding images, this will be released this weekend or next week.

**Comment by dducro** [comment]
The attack modifier decks were added in version 3.13.
