### ISSUE TITLE
Syntax bug in FontSwitch

### ISSUE THREAD

**Issue by 1seanr** [teamducro/gloomhaven-storyline#225]
This might already be fixed in a feature branch but when having a look at the improvements I noticed a bug in the FontSwitch.vue file where it is missing 2 speech marks. I think this is causing the body text to not change when the 'storyline' font checkbox is ticked.
I think it is minor enough to push through another branch rather than making one for it.

File: resources/js/components/elements/FontSwitch.vue
Line: 121
Branch: master and development

Problem: `'div[class*="mdc-"], .bedge',`
Solution: `'div[class*="mdc-"]', '.bedge',`

**Comment by dducro** [comment]
Thanks, This commit should solve the issue: 736bbf7ad369dd1360feaf68feb375528c291835
