### ISSUE TITLE
Adding events in Crimson Scales

### ISSUE THREAD

**Issue by rlambert27** [teamducro/gloomhaven-storyline#226]
Just wondering if it's normal that we can't add any events for Crimson Scales? I see the base 30 events but when we created new characters I wanted to add the new character event cards but was unable to as they don't show up. Thanks!

**Comment by dducro** [comment]
Thanks for reporting, yeah, I would like to add them with a future update.
I'm not sure when, currently most development time goes to FH.

**Comment by rlambert27** [comment]
If you need help let me know, wouldn't mind giving a hand.

**Comment by dducro** [comment]
There was something wrong with the CS events indeed, fixed it and you can add events till 60 now.

**Comment by rlambert27** [comment]
Awesome, thanks!
