### ISSUE TITLE
CS suggestion : Filter GH items based on prosperity

### ISSUE THREAD

**Issue by rlambert27** [teamducro/gloomhaven-storyline#237]
Hello,

Just a suggestion but when enabling the items from other games, obviously GH items will be needed they should be filtered by the current prosperity level in the campaign. 

Currently ALL the GH items appear making the list super long, my opinion is that it should only include the available items from GH based on the current prosperity level.

Thanks!

**Comment by dducro** [comment]
Thanks for the suggestion, this was my plan for CS, just didn't got around to filter the list yet, will be added.

**Comment by dducro** [comment]
When enabling GH items in a game that has prosperity, the items are filtered
