### ISSUE TITLE
Scenario 33: Incorrectly blocked

### ISSUE THREAD

**Issue by conerck** [teamducro/gloomhaven-storyline#24]
Scenario 33 will be blocked when either scenario 34 or 42 is completed.
This is not correct, since the requirement is "The Voice’s Command (Party) **or** The Drake’s Command (Party) COMPLETE"  and 34 only removes "The Drake's Command", and 42 removes "The Voice's Command". Having either of these incomplete, should result in 33 being available.

I'd gladly help out, but I think it would be prudent to first implement the Achievements and then redo the unlocking/blocking logic based on those, since the current approach is bound to run into problems with other consteallations, as well I think.

**Comment by conerck** [comment]
Just checked some other constellations regarding City Rule Achievements and Artifact achivements and they also have problems.

As I said, I'd be more than happy to help you with the Achievements implementation but I guess it we should talk about how to do it first.

**Comment by dducro** [comment]
Thanks, I would appreciate your help on the Achievements.
It's indeed the next thing on the list for me.
I was thinking of a page with 2 lists of achievements, the party and global.
However, I want the user to only manage completed scenario states, and not the achievements them selves. (mostly, if there are means of getting achievements via other methods, only in these cases should the user be able to set if the party has unlocked the achievement.)
Please send me an email at info@danield.nl, we can discuss the details in chat.
Thanks!

**Comment by dducro** [comment]
@conerck Could you check on the current dev build if 33 is fixed?
https://develop--gloomhaven-storyline.netlify.com/#/story
(this might be a temporary fix)

**Comment by conerck** [comment]
Still not working correctly.

33 is now not blocked when completing 34, but it remains unlocked even if you do not have 24 complete.

Basically your logic now is

Blocked = 34.isComplete && 42.isComplete

it should be
Blocked = (25.isComplete && !34.isComplete) || (24.isComplete && !24.isComplete)

Your approach would work if it was based on the granted achievements, instead of completed scenarios, though.

I'll try to have the basic version of the Achievements ready for review by Saturday. Then we can discuss how to best do the unlock logic from there.

**Comment by dducro** [comment]
Yeah, true, thanks!
The problem in this case is that we haven't played scenarios 33 and others in that area with our party.
I think adding the achievements will solve these cases.

From a user perspective it should work like:
- user completes scenario A
- scenarios B and C are unlocked
- achievements are added or removed from the list
- requirements are updated
- for achievements that can be unlocked via other ways then completing scenarios, the user can change its state to update/correct the story-state.
- I also want to add the related scenarios to an achievement, so you can easily find a scenario by its achievement and vice versa.

We need to think of a way to fix the storyline after a user sets a scenario to incomplete, this can cause lots of achievements to be lost and scenarios to be locked.

**Comment by dducro** [comment]
Requirements for scenario 33 are fixed.
