### ISSUE TITLE
CS - Personal quest - #343 - Cruel Dominion

### ISSUE THREAD

**Issue by rlambert27** [teamducro/gloomhaven-storyline#243]
Hello,

One of the kids picked PQ 343 and the title is Cruel Dominion. I was confused because in the CS files section it does actually refer to "The dying of light". I checked the [errata](https://onedrive.live.com/?authkey=%21AHP%2DNpOQEnEJ%2DGo&cid=2B9DA7F60E1EDB15&id=2B9DA7F60E1EDB15%218158&parId=2B9DA7F60E1EDB15%218137&o=OneUp) and just 4 hours ago the 343 card was updated to the correct text. 

I'll submit a PR for the title change but the image will need to be updated. Thanks!

**Comment by dducro** [comment]
Fixed 😃
