### ISSUE TITLE
Scenario 17 not unlocked

### ISSUE THREAD

**Issue by Seroczynski** [teamducro/gloomhaven-storyline#264]
Looted the treasure in scenario 37, nothing shows up. Checked the closed issues but they didn't offer a solution.

![image](https://github.com/teamducro/gloomhaven-storyline/assets/10141349/45a21e8b-d8a6-4371-8143-941fee776828)

https://gloomhaven-storyline.com/tracker/?code=CGZJOG&to_page=story#/campaigns

**Comment by dducro** [comment]
Thanks for reporting, a recent update resulted in this issue, I'll fix this. scenario 17 should be unlocked.
