### ISSUE TITLE
[FH] Scenario 17, 72 and 115 incorrectly unlocked

### ISSUE THREAD

**Issue by pikdonker** [teamducro/gloomhaven-storyline#265]
First of all, thanks very much for the hard work on supporting Frosthaven! Noticed this weekend that it was enabled in beta. So I put in our campaign, and noticed a couple minor faults:

We have completed scenario 9 and scenario 71. According to the app scenario 9 unlocks 17 and 71 unlocks 72, but this is wrong for both cases. We haven't unlocked 17 and 72 in game, so I'm not quite sure how they are unlocked, but it's not by completing 9/71..

**Comment by dducro** [comment]
Thanks for the report, I'll take a look, could you send me your campaign? Thanks.

**Comment by pikdonker** [comment]
@dducro, added scenario 115 to this, it's unlocked in the app after completing 114, in the game it isn't, there's a calendar section added. So this whole issue is probably you guys working on a mechanism to implement delayed scenario unlocks.. Thanks again for your work!

**Comment by dducro** [comment]
Thanks, scenario unlocks like via calendar sections will be supported in the next feature update!

**Comment by dducro** [comment]
#274 Will solve this.
