### ISSUE TITLE
FH Feature Request: Add sled/boat/rope to scenario requirements.

### ISSUE THREAD

**Issue by Kafei56** [teamducro/gloomhaven-storyline#278]
As it stands now there is no indication that these are required for applicable scenarios.

**Comment by dducro** [comment]
I'd like to add this. However, I'll like the scenario to become required as well.
This will need some additional stuff to be implemented, so might release later or in stages.

**Comment by Kafei56** [comment]
I'm not sure what you mean but what it be possible to just have an icon somewhere or maybe a notification when you start the scenario? Maybe in the scenario effects popup?

**Comment by dducro** [comment]
I mean that the scenario is marked with a requirement with an orange **!** and you can't set the scenario to completed unless the party has a boat for example. The scenario will become available automatically after adding the requirement in the buildings tab.

**Comment by dducro** [comment]
in progress, will be released soon.
