### ISSUE TITLE
Frosthaven - 2 campaigns

### ISSUE THREAD

**Issue by rlambert27** [teamducro/gloomhaven-storyline#285]
Hello!

So I play with 2 different groups (friends and kids) and we're starting a new campaign with the kids. I've already paid for access to FH with my friends group, do I need to pay a second time to play a new campaign with my kids? 

Roch

**Comment by dducro** [comment]
Sorry for the late reply.
You can use one free local campaign, but make sure you back it up by sharing a link with your self once in a while. For automatic backups and syncing, please purchase an other shared campaign.
