### ISSUE TITLE
[FH] Scenario 114 state can't be saved

### ISSUE THREAD

**Issue by scottmk** [teamducro/gloomhaven-storyline#287]
Scenario 114 won't properly unlock or complete for me. Every time I click "incomplete" or "complete, I get an error `Something went wrong, please refresh and try again.` When I refresh, the scenario is gone.

If I don't refresh, and I go look at the map, for example, it is there on the map, so everything is working mechanically, but the state is not being saved for scenario 114.

**Comment by egbertwietses** [comment]
Hey, can you try it again? I pushed an update to fix something in FH campaigns. Hope it also solves your issue. If not, I'll investigate more.

**Comment by dducro** [comment]
Hey, can you try it again? I pushed an update to fix something in FH campaigns. Hope it also solves your issue. If not, I'll investigate more.

**Comment by scottmk** [comment]
Yep, that fixed it. Thanks!
