### ISSUE TITLE
[FH] Deathwalker has an extra card

### ISSUE THREAD

**Issue by scottmk** [teamducro/gloomhaven-storyline#288]
There's an extra ability card for Deathwalker that doesn't load. The asset link is `https://gh-storyline.ams3.cdn.digitaloceanspaces.com/img/abilities/fh/DW/shadow-beast.jpg`.

It seems to be the only asset that is `jpg` instead of `webp`, but also there is no card with that name. The shadow beast is a summon on the `Sunless Apparition` card, which does show up in the list.

With this extra card that won't load, there are 12 level 1 cards where there should be only 11, so I think it's safe to assume this one is an extra by mistake.

**Comment by scottmk** [comment]
Looks there's another one, also for a summon.

`https://gh-storyline.ams3.cdn.digitaloceanspaces.com/img/abilities/fh/DW/shadow-horror.jpg` also should not be there.

**Comment by dducro** [comment]
Thanks, fixed: 209dea2a10a34d69ebb20f0fa7cafb927d53bbdf
