### ISSUE TITLE
[FH] Attempting to add items from Gloomhaven adds the wrong items

### ISSUE THREAD

**Issue by powellcj12** [teamducro/gloomhaven-storyline#292]
According to the "Item Supplies" section of the _Frosthaven_ rules (page 58):
> ...certain items from that game can cross over into _Frosthaven_ as options in the available purchase supply, but only if those items are already available in _Gloomhaven_.
>
>At the start of the _Frosthaven_ campaign, **only items 10, 25, 72, 105, 109, and 116 are available**, but other items will becomes available...

Right now when I enable _Gloomhaven_ items in my _Frosthaven_ campaign though, it appears to add items 1-21 from _Gloomhaven_. As best as I can tell, `refreshItems` will call into `calculateItemsGh` ([link](https://github.com/teamducro/gloomhaven-storyline/blob/23d6a82ed6bbb708f94a34b396feece49e9549e5/resources/js/pages/Items.vue#L273)). Based on the comments in `calculateItemsGh`, it seems like it assumes it's only called in the context of _Crimson Scales_? I think I understand the logic, but needing to only selectively add items from other games (as opposed to just assuming all up to a certain amount, based on prosperity of the current game, etc.) might need a bit more work than just changing which items get added statically...

Not sure if there's any current thinking on this topic, I only just found this app/project (really helpful for my group's campaign, I encountered this and very quickly got us a shared campaign!) so eager to help if I can.

**Comment by dducro** [comment]
Thanks for your support, you're correct. It doesn't support a select list of items at the moment. The feature was added for CS and enabled for other games so players could use it if they want.

Do you have suggestions on how to allow the user to select specific GH items in FH? Please suggest solutions PR's are always welcome!

**Comment by powellcj12** [comment]
There might be a couple ways to iterate here, but ultimately what I'm thinking is that upon enabling the checkbox of another game it would reveal additional numbered item checkboxes to enable bringing over specific items from other campaigns. So in my case, we never actually unlocked _all_ of the items that can be brought from _Gloomhaven_ so wouldn't want to just automatically enable all possible items from other games (though that might be a decent first step to at least bring over all possible correct items instead of incorrect ones). This hopefully illustrates what roughly is in my head:

<img width="998" alt="GloomhavenItemSelect" src="https://github.com/teamducro/gloomhaven-storyline/assets/1330113/bac239e7-428e-4dd5-8a5b-867637f3bf97">

The rules do also say that other items will eventually become available on building construction - initially I was thinking that that could mean that it would be good to leverage building state to know which checkboxes even appear here, but it might be better to just show all possible _Gloomhaven_ items and let users manage manually (similar to what is just done with the _Frosthaven_ items list). I'm trying to avoid spoilers so don't know what the ultimate end state might need to be. 😃 

I've got a successful local build so will see if I can play around with things and submit some ideas. If nothing else, just wanted to make sure there wasn't already some thinking behind how to approach this.

**Comment by powellcj12** [comment]
Just wanted to mention that I'm ever-so-slowly playing around with things here - I have no idea how long it might be until I have something that's actually worth of submission, but in case anyone else was interested: https://github.com/powellcj12/gloomhaven-storyline/commits/fh-items/
