### ISSUE TITLE
Improve UX for adding / removing gold / xp

### ISSUE THREAD

**Issue by JanStevens** [teamducro/gloomhaven-storyline#295]
Hi 👋 ,

A small UX suggestion, the ability to add or remove XP and gold instead of increment / decrease by one.

After a scenario you often have to add 12 gold and 18 xp. Having a "change" button that opens a modal to "add" and "remove" the 12 gold or 18 XP greatly improves the experience of the app.

Right now I have to press 12 times on the + (often hitting the -) or manually add the xp and gold myself (and often make small mistakes).

This interface could also be used in other places that deal with adding / removing values.

Regards,

**Comment by JanStevens** [comment]
Hi,

Rather something like this:

![IMG_71058F617C84-1](https://github.com/teamducro/gloomhaven-storyline/assets/1540483/dc9d5a0b-6772-4688-8bf8-ee8412d29879)

Right now I have to manually add 2 numbers (it's simple math but at the end of a long session mistakes happen a lot), also typo's become a lot more common (ex: 234 instead of 243).

The above screenshot is a simple UI: I earned 16 gold so I add it, same with removing gold in case of a negative road event outcome.

I hope this clarifies the request, 

Regards

**Comment by dducro** [comment]
I see, thanks for the suggestion, I'll see if i'm gonna add it.

**Comment by dducro** [comment]
Will be release in next update e56be7cc91e7dd247ae281acffc75cf50b7b1e8c
