### ISSUE TITLE
Buying shared campaing button not working

### ISSUE THREAD

**Issue by Maffey** [teamducro/gloomhaven-storyline#299]
Clicking on "buy shared campaing and selectin Gloomhaven, causes following pop-up to show in the bottom right corner:

![obraz](https://github.com/teamducro/gloomhaven-storyline/assets/29554828/59953079-f9ea-450a-ab5b-323fe3d086b5)

The response from the request that is executed when accessing the button to buy returns 404 error.

**Comment by dducro** [comment]
Thanks for reporting, will fix this today.

**Comment by dducro** [comment]
Fixed
