### ISSUE TITLE
Switching beetween characters

### ISSUE THREAD

**Issue by Pittlhuillier** [teamducro/gloomhaven-storyline#300]
Hi!
Thanks and congrats for this app, it’s awesome!
I can’t switch beetween the two characters of my party and can’t figure why. I’ve tried basically everything (clicking on the second one, swiping screen left or right... ) but all I can do is switching their order in the left list, which doesn’t give me access  to the second one infos.
Did I miss something?
Tanks again,  nice work you did there!

**Comment by dducro** [comment]
Do you still have this issue? I don't and it's difficult to figure out why it's happening. What browser / os /versions are you using? Thanks

**Comment by dducro** [comment]
I disabled dragging characters on touch screens, this should fix your issue.

**Comment by Pittlhuillier** [comment]
Hi, sorry for the late answer. I just tried and everything is working fine!
Thanks a lot :)

Le jeu. 26 sept. 2024, 01:52, Daniël Ducro ***@***.***> a
écrit :
