### ISSUE TITLE
Add "Scenario Level" box

### ISSUE THREAD

**Issue by JStanula** [teamducro/gloomhaven-storyline#303]
Hi, 
This project is really amazing but I was surprised when I couldn't find any option to set nor check Scenario Level. IMHO it's basic function and really easy to implement considering how it's calculated.
Please add this function cause it's essential for gameplay to track it and it's easy to add it.

**Comment by dducro** [comment]
Will be added in upcoming release b234e9a22829faf52d1f798b7120926f2c5ff0b9
