### ISSUE TITLE
Add summary to Sealed scenarios

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#34]
These few scenarios are missing the events that unlocked them.

**Comment by dducro** [comment]
@tomasvanrijsse Could you right a summery of the events that unlocked them?

**Comment by tomasvanrijsse** [comment]
In our party we've only unlocked one of the five sealed scenarios. I can add a summary for that one :)

**Comment by dducro** [comment]
First two 😅
We'll add summaries as we unlock them, please contact me if you want to contribute.

**Comment by GinoGalotti** [comment]
Was going to add the summary of Scenario 72 (just unlocked), but there is nothing like that on the quest log... is it? I can't do the writing myself, it would sound awful

**Comment by dducro** [comment]
We unlocked 4 out of 5, so summaries coming up in a future update.
