### ISSUE TITLE
Button "Pages" should try to open Gloomhaven Scenario Viewer app

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#36]
If they could implement an intent for Gloomhaven pages it would be possible to open their app instead of showing the complete page with spoilers.

we might as well add a suggestion in our app to install theirs.

**Comment by dducro** [comment]
https://play.google.com/store/apps/details?id=com.gmail.roygon.Gloomhaven_Scenario_Viewer&hl=en

**Comment by dducro** [comment]
Contacted the developer twice.

**Comment by tomasvanrijsse** [comment]
Perhaps we could ask Isaac or his publisher for other contact methods. They've probably had contact with this developer

**Comment by dducro** [comment]
Will revisit this issue when scenario viewer gets the frosthaven update.
