### ISSUE TITLE
Scenario should have a single summary instead of multiple

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#38]
Some scenario's have multiple summary texts.
As far as I've seen these texts overlap and are basically saying the same.
`scenarios.json` should be checked for scenario's with multiple quests.

In the branch `feature/revised-quests` some scenario's have been corrected already

**Comment by dducro** [comment]
In these cases most of the time its because the scenario is unlocked via multiple ways. These should be checked and the logic of the states refined so when ever possible only one is visible at any time.
