### ISSUE TITLE
Missing link to Scenario 17

### ISSUE THREAD

**Issue by conerck** [teamducro/gloomhaven-storyline#41]
Scenario 17 can be reached from the Chest reward in scenario 37. There is no arrow to connect these two.

**Comment by dducro** [comment]
True, I purposely didn't implement this arrow.
I think it would make the flowchart less readable.
The scenario is unlocked when this treasure is checked.
In my opinion it's ok to leave the _Lost Island_ without an arrow, we can add a new quest with some text (and only show it if the scenario is unlocked but not chosen by 13) to provide some explanation on how it was unlocked via the treasure.

**Comment by conerck** [comment]
Fine, but that seems inconsistent with the 39 ->15 arrow.

The quest is already there, so no need for a new one.

**Comment by dducro** [comment]
Hmm, true, I'll think about it.

About the quest, the logic needs to be changed because when the scenario is unlocked via the treasure the text states you chose power in 13, that isn't correct.

**Comment by Constantin-Init** [comment]
It's related to this discussion https://github.com/teamducro/gloomhaven-storyline/pull/39#discussion_r420061271

Tomas deleted the extra quest for 17. He was gonna readd it. If we want to be perfect about it, we also need to adjust the quest logic to include the choice in 13, yes. 

Same applies to scenario 15.

**Comment by tomasvanrijsse** [comment]
> It's related to this discussion [#39 (comment)](https://github.com/teamducro/gloomhaven-storyline/pull/39#discussion_r420061271)
> 
> Tomas deleted the extra quest for 17. He was gonna readd it. If we want to be perfect about it, we also need to adjust the quest logic to include the choice in 13, yes.

FYI the quest text for 17 has been restored. https://github.com/teamducro/gloomhaven-storyline/commit/183e4231f7fc315e7763c07aa4fe813e34c85d10

**Comment by dducro** [comment]
I'll add the scenarios to the next and prev links in the modal.

**Comment by dducro** [comment]
I'm closing this issue for now, might look into the arrow later.
