### ISSUE TITLE
Chapter 3 title contains spoilers

### ISSUE THREAD

**Issue by conerck** [teamducro/gloomhaven-storyline#42]
The chapter 3 title contains a spoiler.
You first access this chapter through scenario 5 at which point you have no knowledge of a Demon.

I'd suggest simply renaming it to "The Rift". That would still be a small spoiler if you have unlocked, but not attemted/completed scenario 5, as the rift is only revealed in this scenario.

Alternativly/Additionally we could move scenarios 4,5,6 to their own chapter ("Raiding Crypts" or "The Cultists" maybe) since technically putting 6 in the "The Merchant" chapter is also somewhat of a spoiler.

**Comment by conerck** [comment]
Just realized you could in theory get to scenario 22 and unlock 35/36 without doing 5 or even 4, so the title "The Rift" would also be a spoiler if you get at it from that angle.

I guess it's impossible to be completely spoiler free.

**Comment by dducro** [comment]
I'm thinking to show the chapter titles after the first scenario in a chapter is completed.
Or just hide the titles all together.

I don't want to change the svg in this case.

**Comment by conerck** [comment]
You could, in theory discover the rift and close it without ever meeting the demon (5->19->27), so I still think the title is chosen poorly.

**Comment by dducro** [comment]
(5->19->27) is exactly what we did with our party.
How about removing the titles all together, it's hard to come up with spoiler free titles that do make sense in all situations.

**Comment by dducro** [comment]
Haha, or multiple titles per chapter, depending on the state of the scenarios. #overkill

**Comment by dducro** [comment]
The chapter is shown after the first scenario is completed.
[https://github.com/teamducro/gloomhaven-storyline/commit/6ef2d09ebc8e8adf68ac2f585fbb85836a3d9224](6ef2d09)
This reduces spoilers in most chapters.

Please let me know if you think of an other title for the "Demon and Rift".
