### ISSUE TITLE
The gloom stages shouldn't mention Jekserah to spoilery

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#43]
>I understand where you are coming from:
Until you do scenario 6 there is no price on Jekserah's head from the Bandits, so why would turning against Jekserah have any significance for them.
>
> But on the other hand, the entire campaign started with Jekserah hiring you to steal back the scrolls about the Gloom from them. So, before killing her you had two people/groups connected to the Gloom: The bandits and Jekserah. With her out of the picture, the bandits are the only lead on the Gloom. I think this connection can be made in the quest.
>
> I'll try to think of a way to include Jekserah in the storyline without being too spoilery. The whole part about her head needs to be removed anyway, because you could do scenario 20 before doing 6, in which case her head has already been given to the Captain of the Guard, and can't be given to the bandits anymore.

_Originally posted by @conerck in https://github.com/teamducro/gloomhaven-storyline/pull/39_

**Comment by dducro** [comment]
@conerck What do you think about this issue?
