### ISSUE TITLE
Remove Quest titles 

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#44]
The quest titles give away a certain sense of direction where there's no such clue in the book.
I propose to remove these titles and show 'Preceding events' for new scenario's and 'Summary' as the title when the scenario is completed.

For scenario's with multiple quests it should simply combine the texts (just as it is now but simply by 'hiding' the titles').

**Comment by Constantin-Init** [comment]
I disagree. I think they add flavor. Are there any particular examples that you have a problem with?

**Comment by tomasvanrijsse** [comment]
It's just that I don't prefer to add flavor. I just prefer the sense of being immersed in the world of Gloomhaven. Being immersed in my opinion means getting rid of guides and chapter titles. 

I do want to easily be able to pick the next scenario and therefore need some sort of summary about what happened before each unlocked scenario. But I don't want to see what (made up) quest it belongs to. This most annoying for quests with a lot of connected scenario's, for example Seeking Gloom.

Perhaps it's a bit paranoid about spoilers :)

Another benefit is that this distinction about preceding/summary will also ease other people who are worried to find spoilers in the quests descriptions. It isn't clear straight away that these texts are tailored to the state of the current progress.

**Comment by conerck** [comment]
I dunno. I mean the feedback on the bgg thread where these quests are from is pretty positive. https://boardgamegeek.com/geeklist/237840?commentid=9013944#comment9013944
And I feel the more changes we do the more we disrespect the original work.

**Comment by dducro** [comment]
That's a very good point!
Let's not change it all to try to remove all spoilers, it's also a part of the game.
We could modify some minor things and make it clear that summaries contain content up to the current quest state.
And leave it at that.

**Comment by dducro** [comment]
I will implement 'Preceding events' and 'Summary' for completed scenarios to let the user know it's ok to read it with minimal spoilers, this way the title isn't immediately visible for the user.

**Comment by dducro** [comment]
Addressed in: [89e18d](https://github.com/teamducro/gloomhaven-storyline/commit/89e18de92e2cd5916897d07fbc2af8f9c0e64efb)
