### ISSUE TITLE
Add indicator for skipped treasure

### ISSUE THREAD

**Issue by Bhyn** [teamducro/gloomhaven-storyline#52]
It would be useful if completed scenarios had an indicator that treasure was missed.  Right now it's tedious to find which scenarios to repeat in casual mode.

**Comment by dducro** [comment]
Please use the missed treasures filter on the scenario list view for this.
![Screen Shot 2020-05-14 at 14 41 40](https://user-images.githubusercontent.com/2156884/81935551-19c1a700-95f1-11ea-90f8-94096a18133d.png)

I want to keep the flow chart view as clean as possible, only indicating things needed for the storyline.
