### ISSUE TITLE
Visual bug in achievement modal

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#57]
![CC5ED98C-40ED-4821-97AE-483A5C57FF25](https://user-images.githubusercontent.com/1403466/82014063-17f0f580-967c-11ea-9f10-a72bcafb10bd.png)

The banner looks stretched

**Comment by dducro** [comment]
Haha, don't you like it this way? xD

**Comment by dducro** [comment]
d64f96649512049ad7a1dd11a83133f23a6c4965
