### ISSUE TITLE
Global Achievement from City Card

### ISSUE THREAD

**Issue by marcogpl** [teamducro/gloomhaven-storyline#59]
I gain an Ancient Technology global achievement froma City Card Event, and obviously it's not present in my state. Any other way to add it?

**Comment by dducro** [comment]
Not at the moment, I want to find out which achievements can be unlocked via event cards and add an option to mark them as complete manually.

**Comment by marcogpl** [comment]
ok, thanks!

**Comment by dducro** [comment]
This is available in the current version! 🎉

**Comment by Serneum** [comment]
How does this feature work? I enter in an achievement and hit enter and nothing happens. If I refresh the page, it just goes away.

**Comment by dducro** [comment]
@Serneum Which achievement are you adding? It might be an achievement gained from completing a scenario of one I missed.

**Comment by Serneum** [comment]
@dducro Sun Blessed, which comes from a City Event

**Comment by Serneum** [comment]
@dducro Your comment made me realize it must be some sort of auto-complete. Apparently I was missing the `-` and adding that in made it pop up. Thanks!

**Comment by dducro** [comment]
@Serneum The hyphen is visible on the event card, that's why I added it.
I ignored hyphens in the autocomplete, this should resolve the issue for others!

**Comment by Serneum** [comment]
@dducro Ah, I didn't have the card handy. Gloomhaven Campaign Tracker has it without the hyphen, so they may be wrong. Thanks for the fix!
