### ISSUE TITLE
Should start with achievement City Rule: Militaristic

### ISSUE THREAD

**Issue by Trondster** [teamducro/gloomhaven-storyline#60]
According to the scenario book page 2, a new campaign should start by unlocking scenario 1 Black Barrow, and gaining the achievement City Rule: Militaristic. This is missing.

Thanks for an excellent tool!! :)

**Comment by dducro** [comment]
Thanks, I missed that, will add it in :)

**Comment by dducro** [comment]
de150c84ba3526fedfbd99e1844d7130ae38b383
