### ISSUE TITLE
Storyline not updating on exit.

### ISSUE THREAD

**Issue by Thuddeus** [teamducro/gloomhaven-storyline#61]
I just completed scenario 26 and also unlocked scenario 57. When I exit the program my progress doesn't save. This is a new problem since the move to the new URL.

**Comment by dducro** [comment]
Hmm, I personally don't have this issue.
Could you send me a share link of your progress?
What browser/platform are you using? And could you check if private (incognito) browsing is enabled?
Thanks

**Comment by Thuddeus** [comment]
https://gloomhaven-storyline.com/?choices=13_20&groups=CR_GCRM&states=1_c-2_c-3_c-4_c-5_c-6_c-7_i-8_c-9_b-10_b-13_c-14_c-16_c-18_c-19_c-20_c-22_i-23_c-24_c-25_i-26_c-27_c-28_i-30_c-32_r-42_c-43_i-57_i-63_i&treasures=2_67-4_38_46-5_4_28-6_50-13_10-14_26-16_1-18_63-23_39_72-24_70-26_66
*Nolan Cluff*

**Comment by Thuddeus** [comment]
The link is correct. It seems like a cookie problem.
*Nolan Cluff*

**Comment by dducro** [comment]
What browser are you using? Could you try in Google Chrome without incognito?

**Comment by Thuddeus** [comment]
I am using chrome, and I have never used incognito mode with the story
tracker. For now I am copying the URL at the end of each update. My guess
it's something with my computer/browser combo. Thanks for checking in. I
was mostly curious to see if this was a wide-spread glitch. Since it's not,
I will work through it.
*Nolan Cluff*

**Comment by dducro** [comment]
Ok, great maybe it does work on your phone.

There will come a hosted version in the future, this will keep progress in sync. This will solve the issue when this update rolls out.

**Comment by dducro** [comment]
Thanks for using the tracker!
