### ISSUE TITLE
Allow for multiple campaigns

### ISSUE THREAD

**Issue by brother-oak** [teamducro/gloomhaven-storyline#65]
It would be very useful to be able to load/save states locally - this would enable people to share the state between players, or to manage multiple concurrent campaigns by just loading in the state of the appropriate campaign, then saving it again after changing.

**Comment by dducro** [comment]
Thanks for the suggestion!
I'm working on a hosted version with a sync campaign state feature.
This will enable party members to see each others changes instantly!
This update will be rolled out soon.

**Comment by brother-oak** [comment]
I've just tried out the "share link" option (not sure how recent this is - I don't think it was there previously?) to allow for multiple concurrent campaign tracking, and it (almost) works!
I can set up my campaign track, and then use the "copy link" to store the link. I can then click on that link to reload that campaign.
This works fine, and just means I need to store each campaign link each time I update the campaign.

However, the one problem I have hit so far is with achievements. If for example I have a campaign that has unlocked and completed a few different scenarios, like this one:
https://gloomhaven-storyline.com?groups=CR_GCRM&states=1_c-2_c-3_c-4_i-7_r-8_c-9_b-13_i-14_i-65_i-67_i-82_i&treasures=1_7-8_51

And then I want to load in a campaign that only has scenarios 1 and 2 completed, like this one:
https://gloomhaven-storyline.com?groups=CR_GCRM&states=1_c-2_c-3_i-4_i-69_c&treasures=1_7-2_67

Then it (incorrectly) blocks scenario 3, as it thinks the achievement "Merchant Escapes" (or something like that) is COMPLETE, when for this campaign it is actually INCOMPLETE - I think this is a carry over from loading up the first campaign.

I'm guessing that an 'easy' fix may be to automatically perform a "reset" before loading in a new campaign URL, so achievement states are not left hanging?

**Comment by dducro** [comment]
Hey,

Share link was available from launch. :)

Ah, yes! I was aware of this bug, but forgot about it since I'm working on the new version.
I rolled out a bug fix, it should be working now!

In the new version you can easily switch between campaigns and all party members will be up to date! :)
