### ISSUE TITLE
Sync to cloud

### ISSUE THREAD

**Issue by robertlevy** [teamducro/gloomhaven-storyline#66]
Love this tool!  Thanks for building and maintaining it.  My only problem is having to keep multiple devices in sync.

I’d like to take a crack at adding login and sync capabilities.  I would implement this with Google Firebase where we would presumably be well below the limits of the free tier.  Would you be open to a pull request with this change?

**Comment by dducro** [comment]
Thanks for the suggestion! I'm working on exactly this feature.
Users may sync multiple campaigns and share them among devices, changes will be available instantly.
This will be a payed option to support the project.
Donators wil get early access to test the upcoming build.
