### ISSUE TITLE
Sharing Progress Issue

### ISSUE THREAD

**Issue by t3hWheez** [teamducro/gloomhaven-storyline#67]
When I share the code and open it up, it doesn't save the status of scenario 34.  In our campain this scenario is unavailable and this status never saves through the link.  

Could this be fixed? Here is our progress:

https://gloomhaven-storyline.com?choices=13_15&groups=CR_GCRM-ART_GAR_GAC_GAR_GAC_GAR_GAC&states=1_c-2_c-3_c-4_c-5_c-6_c-7_c-8_c-9_b-10_c-13_c-14_c-15_c-16_c-17_c-18_c-19_c-20_c-21_c-22_c-23_c-24_c-25_c-26_c-27_c-28_c-29_c-30_c-31_c-32_c-33_c-34_b-35_b-36_b-37_c-38_c-39_c-40_c-41_c-42_b-43_c-44_i-46_i-47_i-48_i-52_c-53_c-54_c-61_c-62_c-63_i-64_i-65_i-66_i-67_i-68_c-69_i-70_i-71_i-72_c-73_c-74_c-76_i-78_i-81_i-82_i-83_c-84_i-94_c-95_c&treasures=1_7-3_65-4_38_46-5_4_28-6_50-8_51-10_11-11_5-13_10-14_26-16_1-17_71-18_63-19_17-21_15-22_21-23_39_72-24_70-25_58-26_66-28_32-29_41-31_69-34_23-37_49-38_29-39_73-40_47-41_24-43_35-62_59-68_33-74_20

**Comment by dducro** [comment]
Thanks for reporting this! 👍 
I'll take a look at it over the weekend.

In the meantime, you can open scenario 25, incomplete it, and complete it again, this will give you a prompt witch fixes the storyline state.

**Comment by dducro** [comment]
I already pushed a fix to production! Scenario 34 is now correctly shared via the url!

In the upcoming version you'll have the option to enable automatic sync across party members! In closed beta next week and release sometime after that.
