### ISSUE TITLE
No way to unlock scenarios in non traditional ways [spoiler]

### ISSUE THREAD

**Issue by dangothemango** [teamducro/gloomhaven-storyline#68]
Specifically scenario 17 can be unlocked from a treasure chest but cant be done through this tool with out completing scenario 13

**Comment by dducro** [comment]
In this example storyline I unlocked and completed scenario 17 without completing 13.

By checking the treasure on scenario 37, it unlocks 17.
![Screen Shot 2020-07-10 at 09 14 27](https://user-images.githubusercontent.com/2156884/87127245-ee280980-c28d-11ea-95f4-179da5f8619d.png)

(by clicking this link, your current local storyline will be overwritten)
https://gloomhaven-storyline.test?groups=CR_GCRM-ART_GAR_GAC&states=1_c-2_c-3_b-4_c-5_c-6_c-7_c-8_c-10_c-13_i-14_c-16_i-17_c-18_c-19_i-20_c-21_i-22_c-23_i-26_i-28_i-31_c-35_i-36_i-37_c-38_i-39_i-43_c-47_i&treasures=37_49

**Comment by dangothemango** [comment]
@dducro thanks, didnt think to try this. Didnt feel like going through and backfilling treasure for our campaign. Great tool youve got here.
