### ISSUE TITLE
A way to track donations to the church

### ISSUE THREAD

**Issue by dangothemango** [teamducro/gloomhaven-storyline#69]
Not sure if its on your roadmap but church donations, reputation, and prosperity would be good things to track here

**Comment by dducro** [comment]
Eventually I want to add all these things to the tracker! So you don't have to write some things down and others in here. I'll keep this issue open for when i'm gonna implement it. :)

**Comment by dducro** [comment]
Working on this, upcoming in the next update! :)

**Comment by dducro** [comment]
The party sheet is added! Let me know what you think :)
![Screen Shot 2020-08-31 at 19 39 14](https://user-images.githubusercontent.com/2156884/91749375-ace31480-ebc1-11ea-8225-e74136680a9e.png)

**Comment by dangothemango** [comment]
Looks great! thank you
