### ISSUE TITLE
Completing scenario #14 doesn't unlock scenarios #31 and #43 + Feature request (?)

### ISSUE THREAD

**Issue by gvdb** [teamducro/gloomhaven-storyline#71]
Completing #14 Frozen Hollow unlocks #7 and #19, but not #31 (Plane of Night) and #43 (Drake Nest).

Is this due to a different between printings/editions?

Perhaps a useful feature would be to give users the ability to manually unlock scenarios from the Scenario List?

**Comment by conerck** [comment]
Neither of these 4 is unlocked by scenario 14.

Scenarios are only unlocked if they are mentioned in the "Rewards" section of the scenario.  
If they are mentioned in the conclusion text only, like in scenario 14, it is merely a cue that the story will continue there.

**Comment by gvdb** [comment]
> Neither of these 4 is unlocked by scenario 14.
> 
> Scenarios are only unlocked if they are mentioned in the "New locations" section of the scenario.
> If they are mentioned in the conclusion text only, like in scenario 14, it is merely a cue that the story will continue there.
> 
> 7 and 19 have probably been unlocked for you by different scenarios and completing 14 gave you the required achievement, while 31 and 43 are unlocked through other scenario paths.

Ah yes, I see now. My mistake. Thanks for replying.
