### ISSUE TITLE
Scenario #20 - Wrong name

### ISSUE THREAD

**Issue by verhagenkava** [teamducro/gloomhaven-storyline#72]
Hey, I'm currently going through my first GH campaign and using your app, it works so well!

So I'm just reporting a little bug that I have, looks like the variable for scenario 20 is grabbing more than just the name string or something like that.

The image is attached. Thanks!

![Anotação 2020-07-16 134518](https://user-images.githubusercontent.com/55891479/87699042-a6602100-c76a-11ea-88c9-7991c0634e53.png)

**Comment by dducro** [comment]
Thanks for reporting!
I fixed it and will be available at next release! :)

**Comment by dducro** [comment]
cc38f3289576e3875e6be8d843893d21af2ab2d1
