### ISSUE TITLE
Scenario #62 - Wrong scenario reward

### ISSUE THREAD

**Issue by verhagenkava** [teamducro/gloomhaven-storyline#74]
Hey, just reporting another minor bug that I found while playing. In the Scenario Book, number 62, the end of "The Fall of Men" personal quest opens "Eclipse" character, intead of "Cthulhu" one.

The scenario book link is here: https://online.flippingbook.com/view/145446/80/

The screenshot is here:

![Anotação 2020-07-24 153050](https://user-images.githubusercontent.com/55891479/88423771-b4ddb680-cdc2-11ea-8222-3ce7161ca2f0.png)

Another thing that I'm going to question here, instead of opening another issue, are you guys interested in a Brazilian Portuguese translation? The game got here about 2 months ago and I got one of the not many copies, so I have all the official stuff. That said, I'm still playing the game and will try to avoid too many spoilers, so it might take me a while to do it, but there's a lot in which I could already work on. Thanks!

**Comment by dducro** [comment]
Fixed in: 5cfa4253626a510763bf0eb051722124ab0b2c64
![Screen Shot 2020-08-06 at 23 28 58](https://user-images.githubusercontent.com/2156884/89584726-d9af4080-d83c-11ea-94b5-2ea428e81f34.png)

**Comment by dducro** [comment]
@verhagenkava Translating to Portuguese is very appreciated, is Gloomhaven popular in Brazil?
I understand you can't translate everything.
I might add a button to the site for translators to get in touch.
Please email me at support@gloomhaven-storyline.com, I'll add you to Slack.
