### ISSUE TITLE
Scenario #21 blocks Scenario #21

### ISSUE THREAD

**Issue by sheridaj** [teamducro/gloomhaven-storyline#78]
Scenario 21 awards "The Rift Neutralized" and also requires "The Rift Neutralized" to be incomplete.

Completing Scenario 21 causes the UI to set the status as 'Blocked' instead of 'Complete'. Perhaps more important than the UI bug, if a user incorrectly marked the scenario as complete, there is no way to undo this, as the scenario becomes locked.

**Comment by dducro** [comment]
Thanks for reporting, I'll see what I can do.

**Comment by dducro** [comment]
Could you share your storyline? Thanks.

**Comment by sheridaj** [comment]
https://gloomhaven-storyline.com/?code=ONXNFS#/story

**Comment by dducro** [comment]
Could you verify if your campaign is correctly displayed?

I'm not sure how your campaign ended up in that state, completing 21 should set it to completed and gain the "The Rift Neutralized" achievement. In other words completing a scenario is more important than blocking. I was unable to replicate this state myself. In your case the achievement was gained but the scenario not unlocked.
I may get back to this at a later stage, please give me all info that could help in resolving this issue.
Thanks.

**Comment by sheridaj** [comment]
Whatever you did fixed it. It looks good now. My guess is that it happened during a version upgrade (I was using this app before you added achievements, so probably around then? You're doing the lord's work. It's the only thing I've found that intelligently allows me to track campaigns. Everything else requires way too much manual upkeep)

If you can't reproduce, I'd just close out this ticket and not worry about it. My main concern was if other users got similarly locked out doing relatively common things and it seems as though you've verified that won't happen.

**Comment by dducro** [comment]
Thanks for the info! Yeah, I think it was the upgrade that caused this issue.
With this project and the upcoming updates I hope to help a lot of Gloomhaven players a bit! :)

**Comment by JonasVerhofste** [comment]
This just happened to us as well, and we've only been using the tracker since the beginning of this year. We are using the pro version/cloud sync.

I'll look into this some more the coming days, just wanted to note it down already.

**Comment by JonasVerhofste** [comment]
@dducro I somehow managed to "fix" this by messing around with the states (complete/incomplete) of scenario 5, 19 and 27. It now correctly sets 21 as complete and adds the rift neutralized achievement without blocking 21.

It did seem to have cleared our snapshots. No real problem, but weird nonetheless.

**Comment by dducro** [comment]
A great!
Yeah, I think your campaign was in an invalid state. After updates to the site and unchecking / completing the scenario it fixed the issue. This should not be the case for other campaigns.
