### ISSUE TITLE
Achievements from Events

### ISSUE THREAD

**Issue by elfosardo** [teamducro/gloomhaven-storyline#83]
Currently achievements can be unlocked from scenarios only, but there are events that give achievements as rewards based on the option chosen, for example to Ancient Technology.
There should be a way to unlock Achievements from events or just unlock the Achievements manually.

**Comment by dducro** [comment]
Correct, I agree, this functionality would be very appreciated.
I'm not sure when I can add this.
#59

**Comment by dducro** [comment]
This is available in the current version! 🎉
