### ISSUE TITLE
Scenario 31 should open after completing scenario 14

### ISSUE THREAD

**Issue by LuisGC** [teamducro/gloomhaven-storyline#85]
I have confirmed it with the scenario rules, and it can be seen also in the scanned Pages of the app

**Comment by LuisGC** [comment]
I've just created a pull request that could solve this issue:
#86

**Comment by conerck** [comment]
Nope. These scenarios are not unlocked.

Only scenarios listed in a "New Location" box are unlocked.
Scenarios mentioned in the text are only hints where the story continues.

**Comment by LuisGC** [comment]
Wow, I didn't notice that. I will review if we are not taking it for granted in our game. Thanks!
