### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by alvarofrutos** [teamducro/gloomhaven-storyline#90]
I've started the Spanish translation for the basic elements: GUI, Scenarios and achievements

I'had to be a bit creative regarding the scenario groups as the direct translation sounds strange in Spanish.

I own the Spanish version of Gloomhaven so all achievements and scenarios have the official name.

I have not translated the scenario descriptions since that's a lot of work and I didn't want to spoil myself (I've only played like 15 scenarios). I couldn't translate some achievements neither.

I've created a fork with the modifications.

**Comment by alvarofrutos** [comment]
My branch includes also a fix in the "en.js" file where it says "folowing" instead of "following".

**Comment by dducro** [comment]
Thanks for pointing out the typo! Fixed it in develop branch.

Could you email me at info@gloomhaven-storyline.com? I'll add you to slack, awesome that you started on the Spanish translation! Thanks!
