### ISSUE TITLE
Typo in an achievement name

### ISSUE THREAD

**Issue by jrissman** [teamducro/gloomhaven-storyline#91]
In the Achievements page, when you obtain the party achievement "The Poison's Source" it is displayed in the list as:

achievements.The Poison's Source

It should simply be displayed as:

The Poison's Source

**Comment by jrissman** [comment]
I've attached a screenshot showing the typo.  It is the last achievement listed.

![Screenshot_20210117-114017](https://user-images.githubusercontent.com/7120106/104853932-f3a78180-58b8-11eb-8bb0-026bb9f66fd8.png)

**Comment by dducro** [comment]
Fixed in upcoming release
