### ISSUE TITLE
Gloomhaven Square A/B and Battlements A/B stickers lack red Xs on completion

### ISSUE THREAD

**Issue by jrissman** [teamducro/gloomhaven-storyline#92]
Map board stickers for completed scenarios usually have a red X in the small white checkbox on the sticker.  However, Gloomhaven Square A/B and Gloomhaven Battlements A/B do not get a red X when one version of the scenario is completed.  The correct behavior is to put the red X into whichever check box on the sticker corresponds to the version of the scenario that was completed (A or B).

**Comment by dducro** [comment]
Could you send a screenshot?
The correct red x should be set in A or B after completion.

<img width="804" alt="Screen Shot 2021-01-22 at 23 53 47" src="https://user-images.githubusercontent.com/2156884/105557695-1f899380-5d0d-11eb-9c0f-d22382582bbc.png">
<img width="829" alt="Screen Shot 2021-01-22 at 23 53 18" src="https://user-images.githubusercontent.com/2156884/105557701-20bac080-5d0d-11eb-83ff-54a53cf20015.png">

**Comment by jrissman** [comment]
Sure.  The Xs are missing on the map board view (and also in the scenario popup box for whichever version of the scenario you didn't complete).  Here's a screenshot of the map showing both stickers with both boxes blank.

![Screenshot_20210122-145716](https://user-images.githubusercontent.com/7120106/105558038-86ce2600-5cc2-11eb-8eea-f889ae06e254.png)

Here's a screenshot of the campaign tracker so you can confirm that a version of each of these scenarios has been completed.

![Screenshot_20210122-145732](https://user-images.githubusercontent.com/7120106/105558152-c72da400-5cc2-11eb-9972-1f9a35d391bd.png)

Here's a view of the pop-up for one of the versions of the scenario that was not completed.  The sticker has no Xs.

The only place the red Xs correctly show up is in the scenario pop-up box for the version you did complete.

Showing the Xs on the map board is the most important place, and showing them in the scenario popups is somewhat less important, since some info about completion already appears above in text format in the scenario pop-up.

**Comment by jrissman** [comment]
Sorry, I forgot to attach the third screenshot to the post above.  Here it is.

![Screenshot_20210122-150122](https://user-images.githubusercontent.com/7120106/105558595-c6e1d880-5cc3-11eb-99a8-d8aa51ead0bd.png)

**Comment by dducro** [comment]
Ah, I understand the issue, the scenario stickers are placed on top of each other on the map.
This means that scenarios 12 and 36 are always shown and the issue won't occur on those scenarios.
However when playing 11 or 35 the x is incorrect. Will fix it in next update 👍

**Comment by dducro** [comment]
Fixed, will be published soon!
