### ISSUE TITLE
Ability to remove party achievements in order to track a shared world

### ISSUE THREAD

**Issue by MarkASwanson** [teamducro/gloomhaven-storyline#94]
It would be nice to be able to track the progress of a single party through a single world shared by other parties.

Although a full implementation of this is probably rather complicated, a simple change that could be made would be to allow the deletion of specific party achievements.  This would allow the storyline to show scenarios that have been unlocked by other parties in the world, but still accurately display which achievements your party has and which scenarios it can actually attempt.

**Comment by dducro** [comment]
Interesting, I'll keep this in mind for the future!
You're playing multiple campaigns in the same world?

Only deleting some party achievements won't "fix" it completely. Because you would need a way to put them back. The other playing party should be able to remove other party achievement and you track different things in the party sheet of course.

Or you would have to have 2 separate campaigns and track changes in both of them and then remove some party achievements to "correct" the available scenarios. However, this kinda feels like an incomplete feature.

I'll have to think about it.

**Comment by Constantin-Init** [comment]
I don't think Gloomhaven is supposed to work with 2 parties in the same campaign.
The rules may indicate that, but it is not really feasible.

Going strictly by the rules as written, only one party can ever play any given scenario in campaign mode and get the rewards, which includes achievements. So for example, if party A completes scenario 1 that gives a party achievement "First Steps", which is a requirement for Scenario 2, then when party B plays scenario 1 - going strictly by the rules - the wouldn't get the party achievement "First Steps", and thus wouldn't be allowed to play scenario 2.

The distinction between global and party achievements is more of the line of things that have an impact on the state of the world as whole, and things that only matter to your group of mercenaries.

**Comment by dducro** [comment]
I agree, that's why I "assumed" nobody plays like this :P

I think I'm not totally understanding what you actually mean by this feature request.
Isn't it easier to just track two campaigns for two parties?

**Comment by MarkASwanson** [comment]
For example, your first party completes scenario 1, gets "First Steps", then completes scenario 2, which unlocks 3 and 4 in the world.  At this point, you can start a new party with a different group of people, and either one can play scenario 2 or 3, as there are no party requirements for either.  These parties may affect the world for each other, by increasing prosperity or unlocking side quests, but certain quests will still be available to only certain parties because of party achievement requirements.

We've got three parties going, with a couple people playing in two different parties (so they can play with multiple groups of friends).  This way, they don't have to play the same scenarios over again to get each party to open up their own scenario trees.  It's also kind of cool to feel like you aren't the only adventuring group in the world, and come back for the next play session to see that there's a new item in the shop, or a new side scenario is unlocked.

---

From the perspective of the app (which is awesome, by the way, thank you for putting in the time to build it!), I think this could be accomplished most simply by allowing a party to manually delete party achievements.  You'd have multiple instances of the campaign on the app, and you'd have to update all of them individually each time anything new was unlocked in the world, and then just manually delete any party achievements automatically given when you set a scenario as complete (if you weren't the party that completed it, obviously).

That being said, the only advantage this really provides to each party is a nice interface on the storyline and scenario list pages that marks scenarios your particular party can't do in orange.  Parties could of course make sure to double check the requirements themselves instead.

If this were a feature (or maybe even if it weren't), however, an additional related feature that would add to its utility would be the ability to somehow mark scenarios as "reserved" by certain parties.  Perhaps just a notes section in the scenario modal.  In order to achieve the life goals of their party members, certain scenarios are more "valuable" to certain parties.  It would be nice to be able to keep track of that, assuming the parties wanted to be nice to each other.

---

I kind of assumed this was just the way everybody played!  :P

**Comment by dducro** [comment]
Very interesting!
I only played it with one party and now starting a new campaign (reset everything) with an other group of friends.
I understand what you mean, however I think the option to remove party achievements will bring more confusion then clarity to parties that don't play it that way and mess up there storylines.
So if I implement it, I'd like to completely integrate it so you have to track only one world.
In the mean time, I can add the notes section to the scenario for registered users.
This feature was available a long time ago, but I had to remove it to ensure sharing the storyline in the free option is reliable.
I had other requests in the past for a notes section, so I'll bring it back! :)

**Comment by MarkASwanson** [comment]
That sounds great!  Thanks for indulging me.  I'll be sure to register once the notes feature is in!

**Comment by dducro** [comment]
#e2b5f806391fda429510e5c4614b0d3b53d3d1c2
I added a notes section to the scenarios for registered users!
