### ISSUE TITLE
Subscription vanishes after a few days

### ISSUE THREAD

**Issue by koenix-zz** [teamducro/gloomhaven-storyline#98]
I subscribed / donated to gloomhaven storyline on 23th of February. Since yesterday, the links no longer work and all progress is lost. The issue is not on my end, since none of my companions (that received the shared code) can access our campaign. When I access my campaign link, I end up in a fresh storyline.

I'll also send an email to support@gloomhaven-storyline.com with my storyline link, maybe that provides some insight on what happened.

**Comment by dducro** [comment]
Support is in progress to get access to your account, no campaign data is lost! :)

**Comment by dducro** [comment]
@koenix-zz : "wooohooo! That was super quick - thanks a bunch!"
